flask_app/report/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user
from flask_login.utils import login_required
from pymongo.common import validate

from ..forms import ReceiptForm, SearchForm
from ..models import Receipt, User
from ..utils import current_time
from werkzeug.utils import secure_filename
import random
from datetime import datetime
import plotly.express as px
import io
from pathlib import Path

from ..utils import get_b64_img

report = Blueprint('report', __name__)

@report.route("/", methods=['GET', 'POST'])
def home():
    if current_user.is_authenticated:
            return redirect(url_for("report.summary"))

    return render_template("home.html")

@report.route('/summary', methods=['GET', 'POST'])
@login_required
def summary():
    date_form = SearchForm()
    if date_form.validate_on_submit():
        date = date_form.date.data
        receipt_date = list(Receipt.objects(date=date.strftime("%Y-%m-%d"), user=current_user._get_current_object()))
        receipt_month = list(Receipt.objects(date__startswith=date.strftime("%Y-%m"), user=current_user._get_current_object()))
        receipt_year = list(Receipt.objects(date__startswith=date.strftime("%Y"), user=current_user._get_current_object()))
        
        receipt_date = [obj.to_mongo().to_dict() for obj in receipt_date]
        receipt_month = [obj.to_mongo().to_dict() for obj in receipt_month]
        receipt_year = [obj.to_mongo().to_dict() for obj in receipt_year]

        if len(receipt_date) == 0:
            return render_template("summary.html", date=date_form, message="Go upload some receipts!")
        else:
            fig1 = px.pie(receipt_date, values='cost', names='category')
            f1 = io.StringIO()
            fig1.write_html(f1, full_html=False)
        if len(receipt_month) == 0:
            return render_template("summary.html", date=date_form, message="Go upload some receipts!")
        else:
            fig2 = px.pie(receipt_month, values='cost', names='category')
            f2 = io.StringIO()
            fig2.write_html(f2, full_html=False)
        if len(receipt_year) == 0:
            return render_template("summary.html", date=date_form, message="Go upload some receipts!")
        else:
            fig3 = px.pie(receipt_year, values='cost', names='category')
            f3 = io.StringIO()
            fig3.write_html(f3, full_html=False)


        return render_template("summary.html", date=date_form, 
                plot1=f1.getvalue(),
                plot2=f2.getvalue(),
                plot3=f3.getvalue())
        
    return render_template("summary.html", date=date_form)

@report.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    receipt_form = ReceiptForm()
    if receipt_form.validate_on_submit():
        s = receipt_form.date.data.strftime('%Y-%m-%d') + receipt_form.description.data + receipt_form.category.data + f'{random.random()*1000000}'
        img = receipt_form.receipt.data
        receipt = Receipt(
            user = current_user._get_current_object(),
            date = receipt_form.date.data.strftime('%Y-%m-%d'),
            cost = receipt_form.amount.data,
            category = receipt_form.category.data,
            hash =abs(hash(s)) % (10 ** 8),
            description = receipt_form.description.data,
        )

        if img is not None:
            filename = secure_filename(img.filename)
            content_type = f'images/{filename[-3:]}'
            receipt.receipt_img.put(img.stream, content_type=content_type)
        else:
            path = str(Path(__file__).parent)
            with open(path+"/.."+url_for("static", filename='img/default_receipt.jpg'), 'rb') as img:
                receipt.receipt_img.put(img, content_type='image/jpg')

        receipt.save()
        return redirect(url_for("report.receipts", date=receipt.date))

    return render_template("upload.html", form=receipt_form)

@report.route('/receipt', methods=['GET','POST'])
@login_required
def receipt():
    date = SearchForm()
    if date.validate_on_submit():
        return redirect(url_for("report.receipts", date=date.date.data.strftime('%Y-%m-%d')))
    
    return render_template("receipt.html", form=date)


@report.route('/receipts/<date>', methods=['GET', 'POST'])
@login_required
def receipts(date):
    receipts = Receipt.objects(date=date, user=current_user._get_current_object())
    return render_template("receipts.html", receipts=receipts, get_b64_img = get_b64_img)

@report.route('/delete/<date>/<hash>', methods=['GET', 'POST'])
@login_required
def delete(date, hash):
    receipt = Receipt.objects(date=date, hash=hash, user=current_user._get_current_object()).first()
    date = receipt.date
    receipt.delete()
    return redirect(url_for("report.receipts", date=date))

@report.route('/edit/<date>/<hash>', methods=['GET', 'POST'])
@login_required
def edit(date, hash):
    receipt = Receipt.objects(date=date, hash=hash, user=current_user._get_current_object()).first()
    update_form = ReceiptForm(
        amount= receipt.cost,
        description = receipt.description,
        category = receipt.category,
        date= datetime.strptime(receipt.date, "%Y-%m-%d"))
    
    if update_form.validate_on_submit():
        img = update_form.receipt.data
        receipt.date= update_form.date.data.strftime('%Y-%m-%d')
        receipt.description=update_form.description.data
        receipt.cost=update_form.amount.data
        receipt.category=update_form.category.data

        if img is not None:
            filename = secure_filename(img.filename)
            content_type = f'images/{filename[-3:]}'
            receipt.receipt_img.replace(img.stream, content_type=content_type)

        receipt.save()
        return redirect(url_for("report.edit", date=receipt.date, hash=receipt.hash))

    return render_template("update.html", form=update_form, receipt=receipt, get_b64_img = get_b64_img)

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from ..models import User
from werkzeug.utils import secure_filename
import io, base64
from pathlib import Path

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("report.summary"))
    
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        path = str(Path(__file__).parent)
        with open(path+"/.."+url_for("static", filename='img/default_user.jpg'), 'rb') as img:
            user.profile_pic.put(img, content_type='image/jpg')
        user.save()

        return redirect(url_for("users.login"))
    
    return render_template("register.html", title="Register", form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("report.summary"))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("report.summary"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))
    
    return render_template("login.html", title="Login", form=form)

@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("report.home"))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    usernameForm = UpdateUsernameForm()
    profileForm = UpdateProfilePicForm()
    if usernameForm.validate_on_submit():
        try:
            usernameForm.validate_username(usernameForm.username)
            current_user.modify(username=usernameForm.username.data)
            current_user.save()
        except ValueError as e:
            return render_template("account.html", error_msg = str(e), username=current_user.username, 
            image=get_b64_img(current_user.profile_pic.read()), usernameForm=usernameForm, profileForm=profileForm)

    if profileForm.validate_on_submit():
        img = profileForm.picture.data
        filename = secure_filename(img.filename)
        content_type = f'images/{filename[-3:]}'

        current_user.profile_pic.replace(img.stream, content_type=content_type)
        current_user.save()

    return render_template("account.html", 
                username=current_user.username, image=get_b64_img(current_user.profile_pic.read()),
                usernameForm=usernameForm, profileForm=profileForm)

def get_b64_img(image):       
    bytes_im = io.BytesIO(image)    
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {# Profile picture #}
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        {# Greeting #}
        <h2>Welcome, {{username}}</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        {# Username Update Form #}
        <div class="row">
            <div class="col">
              {% if error_msg %}
                <b>{{ error_msg }}</b>
              {% endif %}
              <form method="POST" action="">
                {{ usernameForm.csrf_token }}
                <div class="form-group">
                  {{ usernameForm.username.label }}
                  {{ usernameForm.username(class="form-control") }}
          
                  {% if usernameForm.username.errors and (profileForm.picture.data is none)%}
                  <div class="alert alert-warning" role="alert">
                    {% for error in usernameForm.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% endif %}
          
                </div>
                <div class="form-group">
                  {{ usernameForm.submit(class="btn btn-outline-success") }}
                </div>    
              </form>
            </div>
          </div>
    </div>
</div>
<div class="row">
    <div class="col">
        {# Profile Picture Update Form #}
        <div class="row">
            <div class="col">
              <form method="POST" action="" enctype="multipart/form-data">
                {{ profileForm.csrf_token }}
                <div class="form-group">
                  {{ profileForm.picture.label }}
                  {{ profileForm.picture(class="form-control") }}
          
                  {% if profileForm.picture.errors and (profileForm.picture.data is not none)%}
                  <div class="alert alert-warning" role="alert">
                    {% for error in profileForm.picture.errors %}
                      <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% endif %}
          
                </div>
                <div class="form-group">
                  {{ profileForm.submit(class="btn btn-outline-success") }}
                </div>              
              </form>
            </div>
          </div>
    </div>
</div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.ico')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>BillTrack</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('report.home') }}">BillTrack</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('report.summary') }}">
                    Summary
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('report.receipt') }}">
                    Receipt
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('report.upload') }}">
                    Upload
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/home.html
{% extends "header.html" %}
{% block content %}

<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Welcome to BillTrack</h1>
      <p>This is a tracker for personal finance. Click below to sign up for an account. </p>
      <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">Sign Up»</a></p>
    </div>
</div>

<footer class="text-center">
  <div class="inner">
    <p>Created by Fucheng Li</p>
  </div>
</footer>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <a href="{{ url_for('users.register') }}"><h3>Register here if you don't have an account</h3></a>
    </div>
</div>
<div class="row">
    <div class="col">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-info">
                        <small>{{message}}</small>
                    </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
                <form method="POST" action="">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username(class="form-control") }}

                    {% if form.username.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.password.label }}
                    {{ form.password(class="form-control") }}

                    {% if form.password.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
            </form>
    </div>
</div>
{% endblock %}

flask_app/templates/receipt.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form action="/receipt" class="form-inline my-2 my-lg-0" method="POST">
            {{ form.csrf_token }}
            {{ form.date(class="form-control", placeholder="Search") }}
            {{ form.submit(class="btn btn-outline-success") }}
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/receipts.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for receipt in receipts %}
    <div class="media">
        <img class="mr-3 receipt-img" src="data:image/png;base64,{{ get_b64_img(receipt.receipt_img.read()) }}" alt="">
        <div class="media-body">
        <h5 class="mt-0">
            <a href="{{ url_for('report.edit', date=receipt.date, hash=receipt.hash) }}">
                {{ receipt.description }}
            </a> 
        </h5>
        <h5 class="mt-0">
            ${{ receipt.cost }}
        </h5>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {% if error_msg %}
            <b>{{ error_msg }}</b>
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col">
        <h3>Click <a href="{{ url_for('users.login') }}">here</a> to login if you already have an account</h3>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <div class="row">
            <div class="col">
                <form method="POST" action="">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username(class="form-control") }}

                    {% if form.username.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.email.label }}
                    {{ form.email(class="form-control") }}

                    {% if form.email.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.password.label }}
                    {{ form.password(class="form-control") }}

                    {% if form.password.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.confirm_password.label }}
                    {{ form.confirm_password(class="form-control") }}

                    {% if form.confirm_password.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                </div>
                <button type="submit" class="btn btn-outline-success">Sign Up</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

flask_app/templates/summary.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <form method="POST" action="">
            {{ date.csrf_token }}
            <div class="form-group">
                {{ date.date.label }}
                {{ date.date(class="datepicker") }}
            </div>
            <button type="submit" class="btn btn-outline-success">Search</button>
        </form>
    </div>
</div>

<ul class="nav nav-tabs">
    <li class="nav-item"><a class="nav-link active" href="#Day" aria-controls="home" role="tab" data-toggle="tab">Day</a></li>
    <li class="nav-item"><a class="nav-link" href="#Month" aria-controls="profile" role="tab" data-toggle="tab">Month</a></li>
    <li class="nav-item"><a class="nav-link" href="#Year" aria-controls="messages" role="tab" data-toggle="tab">Year</a></li>

</ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="Day">
        {% if message %}
            <h3> {{message}}</h3>
        {% endif %}
        {% if plot1 %}
            {{plot1|safe}}
        {% endif %}
    </div>
    <div role="tabpanel" class="tab-pane" id="Month">
        {% if message %}
            <h3> {{message}}</h3>
        {% endif %}
        {% if plot2 %}
            {{plot2|safe}}
        {% endif %}
    </div>
    <div role="tabpanel" class="tab-pane" id="Year">
        {% if message %}
            <h3> {{message}}</h3>
        {% endif %}
        {% if plot3 %}
            {{plot3|safe}}
        {% endif %}
    </div>
   
</div>
{% endblock %}

flask_app/templates/update.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <img class="update-pic" src="data:image/png;base64,{{get_b64_img(receipt.receipt_img.read())}}" alt="image">
        <div class="row">
            <div class="col">
                <form method="POST" action="" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.description.label }}
                    {{ form.description(class="form-control") }}

                    {% if form.description.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.category.label }}
                    {{ form.category(class="form-control") }}

                    {% if form.category.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.category.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.date.label }}
                    {{ form.date(class="form-control") }}

                    {% if form.date.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.date.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.amount.label }}
                    {{ form.amount(class="form-control") }}

                    {% if form.amount.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.amount.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.receipt.label }}
                    {{ form.receipt(class="form-control") }}

                    {% if form.receipt.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.receipt.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                </div>
                <button type="submit" class="btn btn-outline-success">Update</button>
                </form>
                <a href="{{url_for('report.delete', date=receipt.date, hash=receipt.hash) }}" class="btn btn-danger" role="button" aria-pressed="true">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

flask_app/templates/upload.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="row">
            <div class="col">
                <form method="POST" action="" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.description.label }}
                    {{ form.description(class="form-control") }}

                    {% if form.description.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.category.label }}
                    {{ form.category(class="form-control") }}

                    {% if form.category.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.category.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.date.label }}
                    {{ form.date(class="form-control") }}

                    {% if form.date.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.date.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.amount.label }}
                    {{ form.amount(class="form-control") }}

                    {% if form.amount.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.amount.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                    {{ form.receipt.label }}
                    {{ form.receipt(class="form-control") }}

                    {% if form.receipt.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in form.receipt.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}

                </div>
                <button type="submit" class="btn btn-outline-success">Upload</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}